### ISSUE TITLE
mlsql-api-console error

### ISSUE THREAD

**Issue by moranrr** [byzer-org/byzer-lang#1018]
when i register new user,clieck "Register" button。Display ``No Persistence provider for EntityManager named mlsql_console``。

server console：
```
[2019-04-12 16:09:14,679][INFO ][org.hibernate.jpa.boot.internal.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
[2019-04-12 16:09:14,680][INFO ][modules.http.processor.impl] Completed 500 in 6ms (ActiveORM: 0ms)     POST /api_v1/user/register



java.lang.NullPointerException
        at net.csdn.jpa.JPA.modifyPersistenceXml(JPA.java:107)
        at net.csdn.jpa.JPA.getJPAConfig(JPA.java:87)
        at net.csdn.modules.http.processor.impl.DefaultHttpFinishProcessor.closeTx(DefaultHttpFinishProcessor.java:48)
        at net.csdn.modules.http.processor.impl.DefaultHttpFinishProcessor.process(DefaultHttpFinishProcessor.java:31)
        at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:203)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
[2019-04-12 16:09:14,681][INFO ][org.hibernate.jpa.boot.internal.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
```

Where is this file ``persistence.xml``?

**Comment by allwefantasy** [comment]
Persistence.xml is auto generated  by ServiceFramework in start up. Can you show me how you start console? Use the build-in script  or java command line?

**Comment by moranrr** [comment]
I compiled and generated the startup script according to the documentation [自助编译打包](https://github.com/allwefantasy/streamingpro/blob/master/docs/gitbook/zh/installation/compile.md):
```
java -cp /opt/mlsql/mlsql-api-console-1.2.0.jar tech.mlsql.MLSQLConsole \
-mlsql_cluster_url http://10.1.1.92:9003 \
-my_url http://10.1.1.92:9002 \
-user_home /opt/mlsql \
-enable_auth_center false \
-config application.yml
```

and i copy`` serviceframework-orm/src/main/java/META-INF/persistence.xml`` to mlsql-api-console project and modified :
```
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
    <persistence-unit name="mlsql_console">
        <properties>
        </properties>
    </persistence-unit>
</persistence>
```

The following error has occurred:
```
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: MlsqlUser is not mapped [ from MlsqlUser as mlsqluser  where (name=:name)   ]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:713)
        at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
        at net.csdn.jpa.model.JPQL.single_fetch(JPQL.java:257)
        at net.csdn.jpa.model.JPQL.singleFetch(JPQL.java:271)
        at tech.mlsql.model.MlsqlUser.findByName(MlsqlUser.java:81)
        at tech.mlsql.api.controller.UserController.userRegister(UserController.scala:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.csdn.modules.http.RestController.filter(RestController.java:139)
        at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:99)
        at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: MlsqlUser is not mapped [ from MlsqlUser as mlsqluser  where (name=:name)   ]
        at org.hibernate.hql.internal.ast.QuerySyntaxException.generateQueryException(QuerySyntaxException.java:79)
        at org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:219)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:143)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:119)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:80)
        at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
        at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:595)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:704)
        ... 21 more
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: MlsqlUser is not mapped
        at org.hibernate.hql.internal.ast.util.SessionFactoryHelper.requireClassPersister(SessionFactoryHelper.java:169)
        at org.hibernate.hql.internal.ast.tree.FromElementFactory.addFromElement(FromElementFactory.java:91)
        at org.hibernate.hql.internal.ast.tree.FromClause.addFromElement(FromClause.java:79)
        at org.hibernate.hql.internal.ast.HqlSqlWalker.createFromElement(HqlSqlWalker.java:331)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElement(HqlSqlBaseWalker.java:3695)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElementList(HqlSqlBaseWalker.java:3584)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromClause(HqlSqlBaseWalker.java:720)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:576)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:313)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:261)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:271)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:191)
```

**Comment by allwefantasy** [comment]
```sql
java -cp .:/opt/mlsql/mlsql-api-console-1.2.0.jar tech.mlsql.MLSQLConsole \
-mlsql_cluster_url http://10.1.1.92:9003 \
-my_url http://10.1.1.92:9002 \
-user_home /opt/mlsql \
-enable_auth_center false \
-config application.yml
```

The key point is `-cp .:`,   cause the ServiceFramework will generate /persistence.xml in that place.
Notice that persistence.xml should be auto-generated by SF. It will not work when you copy it manually.  

here is the template:

```
#!/usr/bin/env bash

java -cp .:${MLSQL_CONSOLE_JAR} tech.mlsql.MLSQLConsole \
-mlsql_cluster_url ${MLSQL_CLUSTER_URL} \
-my_url ${MY_URL} \
-user_home ${USER_HOME} \
-enable_auth_center ${ENABLE_AUTH_CENTER:-false} \
-config ${MLSQL_CONSOLE_CONFIG_FILE}
```

**Comment by moranrr** [comment]
yes! it works, thanks!
