### ISSUE TITLE
你请求的URL地址[/run/script]不存在

### ISSUE THREAD

**Issue by moranrr** [byzer-org/byzer-lang#1029]
我用下面的命令编译mlsql:
```
mvn clean package -Pshade  -DskipTests  -pl streamingpro-mlsql -am   -Pscala-2.11 -Ponline -Phive-thrift-server -Pcarbondata  -Pcrawler -Pdsl -Pxgboost -Pspark-2.3.0 -Pstreamingpro-spark-2.3.0-adaptor
```

并且使用下面的脚本启动：
```
#!/bin/bash

/usr/hdp/2.6.2.14-5/spark2/bin/spark-submit  --class streaming.core.StreamingApp \
--driver-memory 1G \
--master local[*] \
--name mlsql \
--conf "spark.sql.hive.thriftServer.singleSession=true" \
--conf "spark.kryoserializer.buffer=256k" \
--conf "spark.kryoserializer.buffer.max=1024m" \
--conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" \
--conf "spark.scheduler.mode=FAIR" \
/opt/mlsql/streamingpro-mlsql-spark_2.3-1.2.0.jar  \
-streaming.name mlsql    \
-streaming.platform spark   \
-streaming.rest true   \
-streaming.driver.port 9003   \
-streaming.spark.service true \
-streaming.thrift false \
-streaming.enableHiveSupport true
```

然后访问http://127.0.0.1:9002/#/ 在脚本运行页面点击运行，出现下面的错误

```
19/04/16 13:51:23 ERROR http: System processing error
net.csdn.common.exception.RecordNotFoundException: 你请求的URL地址[/run/script]不存在
        at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:90)
        at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
19/04/16 13:51:23 INFO impl: Completed 404 in 2ms (ActiveORM: 0ms)      POST /run/script



19/04/16 13:51:23 ERROR http: System processing error
net.csdn.common.exception.RecordNotFoundException: 你请求的URL地址[/theme-chrome.js]不存在
        at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:90)
        at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
19/04/16 13:51:23 INFO impl: Completed 404 in 2ms (ActiveORM: 0ms)      GET /theme-chrome.js
```

**Comment by moranrr** [comment]
在启动目录下有个application.yml文件，把这个文件删掉就正常了，不知道为什么
