### ISSUE TITLE
打包成功后,启动start-local.sh,失败

### ISSUE THREAD

**Issue by hbisme** [byzer-org/byzer-lang#1169]
7月16日,从master clone了代码

#编译
cd streamingpro
export MLSQL_SPARK_VERSION=2.4
./dev/package.sh

export VERSION=1.3.0-SNAPSHOT
mkdir -p /tmp/mlsql-server/libs
cp  streamingpro-mlsql/target/streamingpro-mlsql-spark_2.4-${VERSION}.jar /tmp/mlsql-server/libs
cp dev/start-local.sh /tmp/mlsql-server
cd /tmp/mlsql-server
#执行
 echo $SCALA_HOME
#scala版本 /usr/local/scala-2.11.12
export SPARK_HOME=/Volumes/myDocument/soft/spark-2.4.2
./start-local.sh

---报错-----------
```
+ /Volumes/myDocument/soft/spark-2.4.2/bin/spark-submit --class streaming.core.StreamingApp --driver-memory 2g --jars /tmp/mlsql-server/libs/streamingpro-mlsql-spark_2.4-1.3.0-SNAPSHOT.jar --master 'local[*]' --name mlsql --conf spark.driver.extraJavaOptions=-DREALTIME_LOG_HOME=/tmp/__mlsql__/logs --conf spark.sql.hive.thriftServer.singleSession=true --conf spark.kryoserializer.buffer=256k --conf spark.kryoserializer.buffer.max=1024m --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.scheduler.mode=FAIR /tmp/mlsql-server/libs/streamingpro-mlsql-spark_2.4-1.3.0-SNAPSHOT.jar -streaming.name mlsql -streaming.platform spark -streaming.rest true -streaming.driver.port 9003 -streaming.spark.service true -streaming.thrift false -streaming.enableHiveSupport true
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at streaming.core.strategy.platform.HiveJdbcDialect$.<init>(HiveJdbcDialect.scala:10)
	at streaming.core.strategy.platform.HiveJdbcDialect$.<clinit>(HiveJdbcDialect.scala)
	at streaming.core.strategy.platform.SparkRuntime.<init>(SparkRuntime.scala:51)
	at streaming.core.strategy.platform.SparkRuntime$.getOrCreate(SparkRuntime.scala:302)
	at streaming.core.strategy.platform.SparkRuntime.getOrCreate(SparkRuntime.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at streaming.core.strategy.platform.PlatformManager$.createRuntimeByPlatform(PlatformManager.scala:207)
	at streaming.core.strategy.platform.PlatformManager$.getRuntime(PlatformManager.scala:221)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:99)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:31)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
19/07/17 15:06:38 INFO util.ShutdownHookManager: Shutdown hook called
19/07/17 15:06:38 INFO util.ShutdownHookManager: Deleting directory /private/var/folders/2g/v8qn38sx4z1dgg4nt0jy5j7c0000gn/T/spark-afff9e04-2d72-40c5-87e9-28b5ec7847b2
```
请教下怎么解决.

**Comment by hbisme** [comment]
解决了,是spark-2.4.2的问题,换到spark-2.4.3就行了
