### ISSUE TITLE
kafka data can only be set to delta or jdbc ?

### ISSUE THREAD

**Issue by lordk911** [byzer-org/byzer-lang#1243]
I'm now using  mlsql-1.5 , I try to read kafka data out and wite to hdfs , I found that json and parqute are not supported. And I tried delta , but I got error with table not exists error : 
```
19/09/23 14:22:07 ERROR streaming.MicroBatchExecution: Query kafkaTest1 [id = 5247f538-db6b-447b-82ee-06babb779298, runId = e5cf8da4-0f46-476a-9afe-9619ca2e5611] terminated with error
java.lang.IllegalArgumentException: requirement failed: table [/tmp/testdb/test_kafka] is not exists
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.sql.delta.sources.MLSQLDeltaSink.addBatch(MLSQLDeltaSink.scala:33)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:534)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
```
 
my code is : 

```
set streamName="kafkaTest1";

!kafkaTool registerSchema 2 records from "bdp-docker-01:9092" test2;

-- convert table as stream source
load kafka.`test2` options 
kafka.bootstrap.servers="bdp-docker-01:9092"
and failOnDataLoss = "false"
as newkafkatable1;

-- aggregation 
select * from newkafkatable1 as table21;


save append table21  
as rate.`/tmp/testdb/test_kafka` 
options mode="Append"
and idCols="USER_ID,USER_IP"
and duration="5"
and checkpointLocation="/tmp/cp01";
```

**Comment by allwefantasy** [comment]
Download the latest [1.5.0-SNAPSHOT](http://download.mlsql.tech/1.5.0-SNAPSHOT/) and try again.  Notice that  you should  add 

```sql
dropDuplicate="true"
```
to the save statement.

**Comment by allwefantasy** [comment]
## Why you may need to set dropDuplicate parameter
I can explain more why you need set `dropDuplicate` true or you should deDeduplicate by yourself. When there are two same rows in the incoming messages, delta does not know to choose which one to do the upsert operation. 

## Is stream sink only support delta && JDBC?
Not really.For now MLSQL support streamJDBC,streamParquet,rate and binlogRate. But you can [save the stream data with batch mode](http://docs.mlsql.tech/zh/stream/batch.html). With this, you can almost write any datasources that the batch mode supports.

**Comment by lordk911** [comment]
Thanks for reply. After use the latest version , delta can write data to hdfs , but not unser USER_HOME which config when starting console : 
```
export USER_HOME=/home/users
```
it write data to hdfs's root path.

**Comment by lordk911** [comment]
And I've tried write hive data to hdfs ,it will write to the path under USER_HOME
```
set savePath = "/tmp/table2";

load hive.`hdm.wms_orders` as table1;

select * from table1 limit 10 as table2;

save overwrite table2 as json.`${savePath}` where fileNum="10";
```

**Comment by allwefantasy** [comment]
USER_HOME  not working is a Bug...... We will fix later.
