### ISSUE TITLE
Failed to start cluster

### ISSUE THREAD

**Issue by sliontc** [byzer-org/byzer-lang#1251]
java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:923)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1715)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.csdn.jpa.type.DBInfo.info(DBInfo.java:50)
	at net.csdn.jpa.type.DBInfo.<init>(DBInfo.java:33)
	at net.csdn.jpa.JPA$CSDNORMConfiguration.buildDefaultDBInfo(JPA.java:322)
	at net.csdn.jpa.JPA.configure(JPA.java:75)
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at tech.mlsql.cluster.ProxyApplication$.main(ProxyApplication.scala:48)
	at tech.mlsql.cluster.ProxyApplication.main(ProxyApplication.scala)
[2019-10-22 21:16:34,158][ERROR][com.alibaba.druid.pool.DruidDataSource] init datasource error
java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:923)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1715)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:146)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:785)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:140)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1355)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1409)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:602)
	at com.alibaba.druid.pool.DruidDataSourceFactory.config(DruidDataSourceFactory.java:327)
	at com.alibaba.druid.pool.DruidDataSourceFactory.createDataSource(DruidDataSourceFactory.java:132)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildPool(DataSourceManager.java:59)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildDataSourceMap(DataSourceManager.java:46)
	at net.csdn.modules.persist.mysql.DataSourceManager.<init>(DataSourceManager.java:29)
	at net.csdn.jpa.model.JPABase.<clinit>(JPABase.java:37)
	at net.csdn.validate.ValidatorLoader.load(ValidatorLoader.java:18)
	at net.csdn.jpa.JPA.configure(JPA.java:78)
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at tech.mlsql.cluster.ProxyApplication$.main(ProxyApplication.scala:48)
	at tech.mlsql.cluster.ProxyApplication.main(ProxyApplication.scala)
[2019-10-22 21:16:34,204][ERROR][com.alibaba.druid.pool.DruidDataSource] dataSource init error
java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:923)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1715)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:146)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:785)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:140)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1355)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1409)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:602)
	at com.alibaba.druid.pool.DruidDataSourceFactory.config(DruidDataSourceFactory.java:327)
	at com.alibaba.druid.pool.DruidDataSourceFactory.createDataSource(DruidDataSourceFactory.java:132)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildPool(DataSourceManager.java:59)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildDataSourceMap(DataSourceManager.java:46)
	at net.csdn.modules.persist.mysql.DataSourceManager.<init>(DataSourceManager.java:29)
	at net.csdn.jpa.model.JPABase.<clinit>(JPABase.java:37)
	at net.csdn.validate.ValidatorLoader.load(ValidatorLoader.java:18)
	at net.csdn.jpa.JPA.configure(JPA.java:78)
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at tech.mlsql.cluster.ProxyApplication$.main(ProxyApplication.scala:48)
	at tech.mlsql.cluster.ProxyApplication.main(ProxyApplication.scala)
[2019-10-22 21:16:34,218][INFO ][com.alibaba.druid.pool.DruidDataSource] {dataSource-1} inited
java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:923)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1715)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:146)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:785)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:140)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1355)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1409)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:602)
	at com.alibaba.druid.pool.DruidDataSourceFactory.config(DruidDataSourceFactory.java:327)
	at com.alibaba.druid.pool.DruidDataSourceFactory.createDataSource(DruidDataSourceFactory.java:132)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildPool(DataSourceManager.java:59)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildDataSourceMap(DataSourceManager.java:46)
	at net.csdn.modules.persist.mysql.DataSourceManager.<init>(DataSourceManager.java:29)
	at net.csdn.jpa.model.JPABase.<clinit>(JPABase.java:37)
	at net.csdn.validate.ValidatorLoader.load(ValidatorLoader.java:18)
	at net.csdn.jpa.JPA.configure(JPA.java:78)
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at tech.mlsql.cluster.ProxyApplication$.main(ProxyApplication.scala:48)
	at tech.mlsql.cluster.ProxyApplication.main(ProxyApplication.scala)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at tech.mlsql.cluster.ProxyApplication$.main(ProxyApplication.scala:48)
	at tech.mlsql.cluster.ProxyApplication.main(ProxyApplication.scala)
Caused by: java.lang.ExceptionInInitializerError
	at net.csdn.validate.ValidatorLoader.load(ValidatorLoader.java:18)
	at net.csdn.jpa.JPA.configure(JPA.java:78)
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	... 7 more
Caused by: java.lang.RuntimeException: can not create datasource
	at net.csdn.modules.persist.mysql.DataSourceManager.buildPool(DataSourceManager.java:63)
	at net.csdn.modules.persist.mysql.DataSourceManager.buildDataSourceMap(DataSourceManager.java:46)
	at net.csdn.modules.persist.mysql.DataSourceManager.<init>(DataSourceManager.java:29)
	at net.csdn.jpa.model.JPABase.<clinit>(JPABase.java:37)
	... 11 more

**Comment by allwefantasy** [comment]
Your MySQL version is too high. Try MySQL 5.7.
