### ISSUE TITLE
使用预编译的安装包启动失败

### ISSUE THREAD

**Issue by peniridis** [byzer-org/byzer-lang#1334]
### Spark 版本
`Spark 2.3.1.3.0.1.0-187 built for Hadoop 3.1.1.3.0.1.0-187`

### MLSQL 安装包版本
`mlsql-engine_2.3-1.5.0-SNAPSHOT]`
同时更换其他版本 1.6及1.4 也启动失败

### 错误日志
```
+ /usr/hdp/current/spark2-client//bin/spark-submit --class streaming.core.StreamingApp --driver-memory 2g --jars /root/mlsql-engine_2.3-1.5.0-SNAPSHOT/libs/ansj_seg-5.1.6.jar,/root/mlsql-engine_2.3-1.5.0-SNAPSHOT/libs/nlp-lang-1.7.8.jar,/root/mlsql-engine_2.3-1.5.0-SNAPSHOT/libs/streamingpro-mlsql-spark_2.3_2.11-1.5.0-SNAPSHOT.jar --master 'local[*]' --name mlsql --conf spark.driver.extraJavaOptions=-DREALTIME_LOG_HOME=/tmp/__mlsql__/logs --conf spark.sql.hive.thriftServer.singleSession=true --conf spark.kryoserializer.buffer=256k --conf spark.kryoserializer.buffer.max=1024m --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.scheduler.mode=FAIR /root/mlsql-engine_2.3-1.5.0-SNAPSHOT/libs/streamingpro-mlsql-spark_2.3_2.11-1.5.0-SNAPSHOT.jar -streaming.name mlsql -streaming.platform spark -streaming.rest true -streaming.driver.port 9003 -streaming.spark.service true -streaming.thrift false -streaming.enableHiveSupport true
20/04/30 10:12:26 WARN SparkRuntime: ------- CarbonData do not support current version of spark [2.3.1.3.0.1.0-187], streaming.enableCarbonDataSupport will not take effect.--------
20/04/30 10:12:27 WARN FairSchedulableBuilder: Fair Scheduler configuration file not found so jobs will be scheduled in FIFO order. To use fair scheduling, configure pools in fairscheduler.xml or set spark.scheduler.allocation.file to a file that contains the configuration.
20/04/30 10:12:34 ERROR impl: load default controller error:java.lang.ClassNotFoundException: 
20/04/30 10:13:26 WARN QueuedThreadPool: 
java.lang.NoSuchMethodError: org.eclipse.jetty.util.StringUtil.toInt(Ljava/lang/String;)I
        at org.eclipse.jetty.http.HttpParser.handleKnownHeaders(HttpParser.java:854)
        at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:968)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1257)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
20/04/30 10:13:26 WARN QueuedThreadPool: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@174d60df in qtp924040924{STARTED,100<=100<=1000,i=94,q=0}

```

求助

**Comment by allwefantasy** [comment]
不支持hadoop 3.0 哦。

**Comment by allwefantasy** [comment]
如果需要配合3.0使用，需要使用mlsql spark 3.0的预编译包：mlsql-engine_3.0-1.6.0-SNAPSHOT.tar.gz 。但是因为正式版的spark 3.0还没有发布,所以这个功能还有不少问题。

**Comment by peniridis** [comment]
好 了解。
