### ISSUE TITLE
适配Greenplum-Spark Connector进行大批量写出错

### ISSUE THREAD

**Issue by panjiebin** [byzer-org/byzer-lang#1397]
为了实现Greenplum大批量写场景，自己扩展了ET功能
Greenplum-Spark Connector 下载 http://greenplum-spark.docs.pivotal.io/2-1/index.html

我下载版本：greenplum-connector-apache-spark-scala_2.12-2.0.0.jar

Greenplumn版本：5.20.1

ET实现：

```scala
override def train(df: DataFrame, path: String, params: Map[String, String]): DataFrame = {
    val options: Map[String, String] = Map("url" -> params.getOrElse("url", ""),
      "user" -> params.getOrElse("user", ""),
      "password" -> params.getOrElse("password", ""),
      "dbschema" -> params.getOrElse("db_schema", ""),
      "dbtable" -> params.getOrElse("db_table", ""),
      "truncate" -> params.getOrElse("truncate", ""))
    df.write.format("greenplum").options(options).mode(SaveMode.Append).save()
    val resRdd = df.sparkSession.sparkContext.parallelize(Seq(Row("successful")))
    val struct = StructType(Seq(StructField("msg", StringType, nullable = true)))
    df.sparkSession.createDataFrame(resRdd, struct)
  }

```

在执行MLSQL脚本:

```sql
connect jdbc where 
url = "${url}" 
and driver = "${driver}" 
and user = "${user}" 
and password = "${password}" 
and fetchsize = "5000" 
as greenplum_db;

load jdbc.`greenplum_db.t_rh_rh_xw_lgtf` as t_rh_rh_xw_lgtf;
--分组统计
select count(*) as total,ssq_mc_w FROM t_rh_rh_xw_lgtf GROUP BY ssq_mc_w AS res;
--自定义ET
train res as GPStorage.`` 
where url = "${url}" 
and user = "${user}" 
and password = "${password}" 
and db_schema = "${db_schema}" 
and db_table = "t_gl" 
and truncate = "false" as output;

```

时会报如下异常：

```
Job aborted due to stage failure: Task 39 in stage 6107.0 failed 4 times, most recent failure: Lost task 39.3 in stage 6107.0 (TID 92797, all4, executor 2): org.postgresql.util.PSQLException: ERROR: http response code 500 from gpfdist (gpfdist://192.168.120.194:11882/spark_568d000145083ea3_3d9d854163f8f07a_2_34868): HTTP/1.1 500 Server Error  (seg0 slice1 192.168.123.23:9000 pid=20241)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at io.pivotal.greenplum.spark.SqlExecutor.$anonfun$executeUpdate$4(SqlExecutor.scala:45)
	at io.pivotal.greenplum.spark.SqlExecutor.$anonfun$executeUpdate$4$adapted(SqlExecutor.scala:43)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:252)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at scala.util.control.Exception$Catch.either(Exception.scala:252)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:27)
	at resource.ManagedResourceOperations$$anon$2.$anonfun$acquireFor$1(ManagedResourceOperations.scala:49)
	at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:252)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at scala.util.control.Exception$Catch.either(Exception.scala:252)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$$anon$2.acquireFor(ManagedResourceOperations.scala:49)
	at resource.ManagedResourceOperations.apply(ManagedResourceOperations.scala:26)
	at resource.ManagedResourceOperations.apply$(ManagedResourceOperations.scala:26)
	at resource.ManagedResourceOperations$$anon$2.apply(ManagedResourceOperations.scala:47)
	at resource.DeferredExtractableManagedResource.$anonfun$tried$1(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:213)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at io.pivotal.greenplum.spark.SqlExecutor.tryFromManaged(SqlExecutor.scala:74)
	at io.pivotal.greenplum.spark.SqlExecutor.executeUpdate(SqlExecutor.scala:42)
	at io.pivotal.greenplum.spark.externaltable.GreenplumTableManager.copyTable(GreenplumTableManager.scala:159)
	at io.pivotal.greenplum.spark.externaltable.GreenplumDataMover.$anonfun$moveData$1(GreenplumDataMover.scala:53)
	at scala.util.Success.flatMap(Try.scala:251)
	at io.pivotal.greenplum.spark.externaltable.GreenplumDataMover.moveData(GreenplumDataMover.scala:50)
	at io.pivotal.greenplum.spark.externaltable.PartitionWriter.$anonfun$getClosure$1(PartitionWriter.scala:39)
	at io.pivotal.greenplum.spark.externaltable.PartitionWriter.$anonfun$getClosure$1$adapted(PartitionWriter.scala:31)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:889)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:889)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

问题补充：
只有在前面语句中存在聚合函数才会出现这个问题，我在聚合函数之后紧接一个排序语句是能解决这个问题。

**Comment by allwefantasy** [comment]
看着像是gp自身的问题？ 目前你代码上看是没啥毛病的。

**Comment by allwefantasy** [comment]
你使用Jdbc接口读取，可能会存在性能问题。SPark默认会使用一个线程去拉取数据，而你 有没有where条件做限制，所以会导致尝试去拉取全量数据。

你可以试着用实现一个gp的数据源。比如：

```
load gp.`...` as gptable;
```

包装很简单的，可以参考下MLSQL已有的一些实现。比如`streaming.core.datasource.impl.MLSQLElasticSearch` 这个是对es数据源的包装。

**Comment by panjiebin** [comment]
这个可能跟数据源没有关系，我的场景里面输入不一定是gp，也可能是常用的关系库，普通关系库也存在该问题，比较疑惑的是只有存在聚合函数时才会出现这个问题，而使用其他函数写是正常的，加个排序却可以。我比较怀疑是否跟spark函数Transformations和Actions的特性有关系

**Comment by allwefantasy** [comment]
> 这个可能跟数据源没有关系，我的场景里面输入不一定是gp，也可能是常用的关系库，普通关系库也存在该问题，比较疑惑的是只有存在聚合函数时才会出现这个问题，而使用其他函数写是正常的，加个排序却可以。我比较怀疑是否跟spark函数Transformations和Actions的特性有关系

参考我这篇文文章： http://docs.mlsql.tech/mlsql-console/qa/load_jdbc.html 。 我不认为会是
Transformations和Actions的问题。

**Comment by panjiebin** [comment]
实际定位到异常
```
20/12/10 17:14:24  DEBUG GpfdistLocation: Creating URI string at gpfdist://10.10.0.244:55683/spark_85f57eb993b98424_3d9d854163f8f07a_driver_231
20/12/10 17:14:24  DEBUG GreenplumTableManager: Create readable external table query: CREATE READABLE EXTERNAL TABLE
"test22"."spark_85f57eb993b98424_3d9d854163f8f07a_driver_231" (LIKE "test22"."t_js_ry_zq_zdrdtgjhz")
LOCATION ('gpfdist://10.10.0.244:55683/spark_85f57eb993b98424_3d9d854163f8f07a_driver_231')
FORMAT 'CSV'
(DELIMITER AS '|'
 NULL AS '')
ENCODING 'UTF-8'
20/12/10 17:14:24  DEBUG SqlExecutor: executing query: CREATE READABLE EXTERNAL TABLE
"test22"."spark_85f57eb993b98424_3d9d854163f8f07a_driver_231" (LIKE "test22"."t_js_ry_zq_zdrdtgjhz")
LOCATION ('gpfdist://10.10.0.244:55683/spark_85f57eb993b98424_3d9d854163f8f07a_driver_231')
FORMAT 'CSV'
(DELIMITER AS '|'
 NULL AS '')
ENCODING 'UTF-8'
20/12/10 17:14:24  DEBUG GreenplumTableManager: External table "test22"."spark_85f57eb993b98424_3d9d854163f8f07a_driver_231" not found, created table with port=55683
20/12/10 17:14:24  DEBUG SqlExecutor: executing query: INSERT INTO "test22"."t_js_ry_zq_zdrdtgjhz"
SELECT *
FROM "test22"."spark_85f57eb993b98424_3d9d854163f8f07a_driver_231"
20/12/10 17:14:24  DEBUG GpfdistHandler: Processing GET for /spark_85f57eb993b98424_3d9d854163f8f07a_driver_231
20/12/10 17:14:46  WARN HikariPool: HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=48s119ms925µs200ns).
20/12/10 17:14:46  WARN HikariPool: HikariPool-3 - Thread starvation or clock leap detected (housekeeper delta=48s119ms914µs300ns).
20/12/10 17:14:46  WARN HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=48s120ms715µs).
20/12/10 17:14:46  DEBUG GpfdistHandler: Processing GET for /spark_85f57eb993b98424_3d9d854163f8f07a_driver_231
20/12/10 17:14:46  DEBUG GpfdistHandler: Successfully handled GET request for /spark_85f57eb993b98424_3d9d854163f8f07a_driver_231
java.lang.NullPointerException
	at org.apache.spark.sql.execution.aggregate.HashAggregateExec.createHashMap(HashAggregateExec.scala:434)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at io.pivotal.greenplum.spark.externaltable.GpfdistHandler.$anonfun$serveData$1(GpfdistHandler.scala:119)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at io.pivotal.greenplum.spark.externaltable.GpfdistHandler.serveData(GpfdistHandler.scala:110)
	at io.pivotal.greenplum.spark.externaltable.GpfdistHandler.processPartitionData(GpfdistHandler.scala:96)
	at io.pivotal.greenplum.spark.externaltable.GpfdistHandler.handleGET(GpfdistHandler.scala:84)
	at io.pivotal.greenplum.spark.externaltable.GpfdistHandler.handle(GpfdistHandler.scala:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

org.apache.spark.sql.execution.aggregate.HashAggregateExec.createHashMap函数中TaskContext.get()返回为空，
还不清楚为什么

```scala
def createHashMap(): UnsafeFixedWidthAggregationMap = {
    // create initialized aggregate buffer
    val initExpr = declFunctions.flatMap(f => f.initialValues)
    val initialBuffer = UnsafeProjection.create(initExpr)(EmptyRow)

    // create hashMap
    new UnsafeFixedWidthAggregationMap(
      initialBuffer,
      bufferSchema,
      groupingKeySchema,
      TaskContext.get(),
      1024 * 16, // initial capacity
      TaskContext.get().taskMemoryManager().pageSizeBytes
    )
  }
```
```sql
select count(*) as total,ssq_mc_w FROM t_rh_rh_xw_lgtf GROUP BY ssq_mc_w AS res;
select * from res order by total as res;
```
聚合函数后跟排序与不加排序多一个shuff的stage
