### ISSUE TITLE
!ray命令使用Ray集群计算时出现socket问题

### ISSUE THREAD

**Issue by panjiebin** [byzer-org/byzer-lang#1423]
mlsql version：mlsql-engine_3.0-2.0.1
Spark version: 3.0.1
spark on yarn

问题描述：

访问9003端口，执行以下语句：
`set mockData='''

{"title":"第一","body":"内容1"}
{"title":"第二","body":"内容2"}
{"title":"第三","body":"内容3"}

''';

load jsonStr.`mockData` as data;

!python env "PYTHON_ENV=:";
!python conf "runIn=driver";
!python conf "schema=st(field(title,string),field(body,string))";
!python conf "dataMode=data";

!ray on data '''

import ray
from pyjava.api.mlsql import RayContext
import numpy as np;

ray_context = RayContext.connect(globals(),"10.254.23.28:6379")

def echo(row):
    row1 = {}
    row1["title"]="jackm"
    row1["body"]= row["body"]
    return row1

ray_context.foreach(echo)

''' named newdata;

select * from newdata as output;`

提交执行后，后台日志首先出现这个异常信息
`

21/04/23 09:15:56 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 10.254.23.30:46600
21/04/23 09:15:57 INFO server.SocketServerInExecutor: Received connection fromSocket[addr=/10.254.23.30,port=41992,localport=40895]
ReportHostAndPort(vans3,33418)
21/04/23 09:15:58 ERROR server.SocketServerInExecutor:
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at tech.mlsql.common.utils.distribute.socket.server.SocketServerInExecutor$$anon$2.run(ExecutorSocketServer.scala:71)
`
过了一段时间后出现以下这个异常信息

`
21/04/23 09:20:59 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 7.0 (TID 11, vans3, executor 1): org.apache.spark.SparkException: Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/api/serve.py", line 66, in serve
    self.out_ser.dump_stream(out_data, out)
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/serializers.py", line 328, in dump_stream
    super(ArrowStreamPandasSerializer, self).dump_stream(batches, stream)
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/serializers.py", line 204, in dump_stream
    for batch in iterator:
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/serializers.py", line 327, in <genexpr>
    batches = (self._create_batch(series) for series in iterator)
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/api/serve.py", line 64, in <genexpr>
    out_data = ([df[name] for name in df] for df in
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/api/mlsql.py", line 85, in build_chunk_result
    for item in items:
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/api/serve.py", line 117, in <genexpr>
    data = (func_for_row(item)
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/api/mlsql.py", line 333, in fetch_once_as_rows
    for df in RayContext.fetch_data_from_single_data_server(data_server):
  File "/usr/local/python3/lib/python3.6/site-packages/pyjava/api/mlsql.py", line 342, in fetch_data_from_single_data_server
    sock.connect((data_server.host, data_server.port))
ConnectionRefusedError: [Errno 111] Connection refused

        at tech.mlsql.arrow.python.runner.ReaderIterator.handlePythonException(SparkSocketRunner.scala:166)
        at tech.mlsql.arrow.python.runner.SparkSocketRunner$$anon$1.read(SparkSocketRunner.scala:99)
        at tech.mlsql.arrow.python.runner.SparkSocketRunner$$anon$1.read(SparkSocketRunner.scala:92)
        at tech.mlsql.arrow.python.runner.SparkSocketRunner$$anon$1.read(SparkSocketRunner.scala:50)
        at tech.mlsql.arrow.python.runner.ReaderIterator.hasNext(SparkSocketRunner.scala:130)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by allwefantasy** [comment]
能简单说明下Ray相关的版本么？

建议按如下方式安装Python依赖库：

```
pip install Cython
pip install pyarrow==0.10.0
pip install ray==0.8.0
pip install aiohttp psutil setproctitle grpcio pandas xlsxwriter
pip install watchdog requests click uuid sfcli  pyjava
```

也就是ray需要是0.8.0版本。 

PS: 我们未来对新版本如ray 0.8.7-1.2.0的版本已经在测试的路上了。

**Comment by allwefantasy** [comment]
另外，这个同学的文章也可以参考下： https://mukvin.com/MLSQL-env-Python-MLSQL-Python-b520ad94f40d45019d81bdd2ae9850cf

**Comment by allwefantasy** [comment]
另外，不妨先测试下基于Spark 2.4.3版本。这个测试使用比较多。

**Comment by panjiebin** [comment]
问题解决了，问题出在mlsql-engine启动命令误配置了executor-cores=1
