### ISSUE TITLE
Running mlsql-lang-cli throws exception

### ISSUE THREAD

**Issue by chncaesar** [byzer-org/byzer-lang#1534]
## Exception:
java.lang.ClassCastException: tech.mlsql.runtime.SparkSubmitMLSQLScriptRuntimeLifecycle cannot be cast to tech.mlsql.runtime.MLSQLPlatformLifecycle
	at streaming.core.StreamingApp$$anonfun$main$1$$anonfun$apply$mcV$sp$1.apply(StreamingApp.scala:41)
	at streaming.core.StreamingApp$$anonfun$main$1$$anonfun$apply$mcV$sp$1.apply(StreamingApp.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at streaming.core.StreamingApp$$anonfun$main$1.apply$mcV$sp(StreamingApp.scala:38)
	at tech.mlsql.common.utils.base.TryTool$.tryOrExit(TryTool.scala:44)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:35)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
21/09/07 14:38:51  INFO JVMShutdownHookManager: Shutdown hook called

Running command: 
```
mlsql run ./hello.mlsql
```
The mlsql cmd is built from https://github.com/allwefantasy/mlsql-lang-cli
It registers SparkSubmitMLSQLScriptRuntimeLifecycle as a lifeCyclePlugin.
However, all liefcycleplugin should extend MLSQLPlatformLifecycle

**Comment by chncaesar** [comment]
Close this issue , as it was fixed in https://github.com/allwefantasy/mlsql/commit/9b78e6909fb9d106b5a87647e489ed1b56a57fb0
