### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: streaming.core.compositor.spark.source.SQLSourceCompositor

### ISSUE THREAD

**Issue by jinky2004** [byzer-org/byzer-lang#196]
我的测试用例
{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "spark",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "streaming.core.compositor.spark.source.SQLSourceCompositor",
        "params": [ {
              "path": " /yarn/offline-platform/tmp/testData.txt ",
              "format": "org.apache.spark.sql.execution.datasources.hdfs",
              "outputTable": "hdfstest",
              "header": "true"
            }
		]
      },
      {
        "name": "stream.sql",
        "params": [
          {
            "sql": "select CAST(value AS STRING) as json from hdfstest",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "stream.sql",
        "params": [
          {
            "sql": "select get_json_object(json, '$.uuid') as id,get_json_object(json, '$.deviceType') as deviceType  from test1",
            "outputTableName": "test2"
          }
        ]
      },
      {
        "name": "stream.outputs",
        "params": [
          {
			  "url":"jdbc:mysql://192.168.1.192:3306/SSA?user=root&password=1qazXSW@3edc",
              "dbtable":"testhdfs",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "console",
			  "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

执行的时候报错
Exception in thread "main" java.lang.ClassNotFoundException: streaming.core.compositor.spark.source.SQLSourceCompositor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$createCompositors$1.apply(StrategyDispatcher.scala:193)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$createCompositors$1.apply(StrategyDispatcher.scala:192)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at serviceframework.dispatcher.StrategyDispatcher.createCompositors(StrategyDispatcher.scala:191)
        at serviceframework.dispatcher.StrategyDispatcher.createStrategy(StrategyDispatcher.scala:142)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$load$1.apply(StrategyDispatcher.scala:131)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$load$1.apply(StrategyDispatcher.scala:130)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at serviceframework.dispatcher.StrategyDispatcher.load(StrategyDispatcher.scala:129)
        at serviceframework.dispatcher.StrategyDispatcher.loadConfig(StrategyDispatcher.scala:125)
        at serviceframework.dispatcher.StrategyDispatcher$.getOrCreate(StrategyDispatcher.scala:247)
        at streaming.core.Dispatcher$.dispatcher(Dispatcher.scala:38)
        at streaming.core.strategy.platform.PlatformManager.findDispatcher(PlatformManager.scala:34)
        at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:84)
        at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
        at streaming.core.StreamingApp.main(StreamingApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

请帮忙看下，是不是测试用例的配置有问题， 我的目标是读取hdfs中的文件，入到mysql

**Comment by jinky2004** [comment]
这个问题，我通过调整json，目前是可以调通的，但感觉spark-2.2.0 方式编译出来的包，会有很多缺失，请大神帮忙看下，谢谢！ 我调整后的json脚本如下：
{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "streaming.core.strategy.SparkStreamingStrategy",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "streaming.core.compositor.spark.source.MultiSQLSourceCompositor",
        "params": [ {
              "path": "/yarn/offline-platform/tmp/testData.txt",
              "format": "json",
              "outputTable": "hdfstest"
            }
                ]
      },
      {
        "name": "streaming.core.compositor.spark.transformation.SQLCompositor",
        "params": [
          {
            "sql": "select hdfstest.*  from hdfstest",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.transformation.SQLCompositor",
        "params": [
          {
            "sql": "select uuid ,deviceType,PRIORITY,PROTOCOL,COLLECT_TIME,PEAK_FLOW,ACTION,SRC_IP,DST_IP,SRC_PORT,DST_PORT,POLICY,eventType_s  from test1",
            "outputTableName": "test2"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.output.MultiSQLOutputCompositor",
        "params": [
          {
                          "url":"jdbc:mysql://192.168.1.192:3306/analysisTest?user=root&password=1qazXSW@3edc",
              "dbtable":"testhdfs",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "jdbc",
                          "mode" : "Append",
                          "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

**Comment by jinky2004** [comment]
先关闭这个问题吧， 目前看是可以支撑的，但关键是很多class not found 的问题，还请大神在另一个提问上帮忙看下，谢谢
