### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by jinky2004** [byzer-org/byzer-lang#199]
大神，您好！
在将parquet文件作为输入，输出到mysql的时候，数据有成功入mysql，但会出现以下异常， 请帮忙看下，谢谢！
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at org.apache.spark.streaming.SparkStreamingOperator.inputStreamId(SparkStreamingOperator.scala:21)
        at streaming.core.strategy.platform.SparkStreamingRuntime.processEvent(SparkStreamingRuntime.scala:122)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3$$anonfun$apply$1.apply(PlatformManager.scala:123)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3$$anonfun$apply$1.apply(PlatformManager.scala:122)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:122)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:116)
        at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
        at streaming.core.StreamingApp.main(StreamingApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)

对应的json脚本如下：
{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "spark",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "batch.sources",
                "params": [{
                 "format":"parquet",
                 "path":"/tmp/venus_waf/testData.parquet",
                 "outputTable": "hdfstest"
             }]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "select hdfstest.*  from hdfstest limit 153318",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "SELECT     DST_IP,   DEVICE_TYPE,  COLLECT_IP,  EQU_IP,  SRC_IP,  PROTOCOL,  SRC_PORT,  ACTION,  DST_PORT,  SERVERITY,  COLLECT_TIME,  CREATE_TIME,  ATTACK_TYPE,  TAG,  TYPE FROM  test1 ",
            "outputTableName": "test2"
          }
        ]
      },
       {
        "name": "batch.outputs",
        "params": [
          {
                          "url":"jdbc:mysql://192.168.1.192:3306/analysisTest?user=root&password=1qazXSW@3edc",
              "dbtable":"test_table",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "jdbc",
                          "mode" : "Append",
                          "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

**Comment by robin-su** [comment]
遇到同样的问题，求教！

**Comment by jinky2004** [comment]
问题解决了，谢谢！
