### ISSUE TITLE
 持久化mysql的ArrayIndexOutOfBoundsException异常

### ISSUE THREAD

**Issue by robin-su** [byzer-org/byzer-lang#203]
**实验场景：通过Spark sql查询parquet文件并将其持久化到Mysql，Json文件配置如下：**
{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "spark",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "batch.sources",
                "params": [{
                 "format":"parquet",
                 "path":"/tmp/venus_waf/testData.parquet",  
                 "outputTable": "hdfstest"                               
             }]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "select hdfstest.*  from hdfstest",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "SELECT     DST_IP,   DEVICE_TYPE,  COLLECT_IP,  EQU_IP,  SRC_IP,  PROTOCOL,  SRC_PORT,  ACTION,  DST_PORT,  SERVERITY,  COLLECT_TIME,  CREATE_TIME,  ATTACK_TYPE,  TAG,  TYPE FROM  test1 ",
            "outputTableName": "test2"
          }
        ]
      },
       {
        "name": "batch.outputs",
        "params": [
          {
                          "url":"jdbc:mysql://xxx.xxx.xxx.xxx:3306/analysisTest?user=root&password=abc",
              "dbtable":"test_table",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "jdbc",
                          "mode" : "Append",
                          "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

**实验结果：**
     注意是在持久化到mysql成功之后，报如下错误：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at org.apache.spark.streaming.SparkStreamingOperator.inputStreamId(SparkStreamingOperator.scala:21)
        at streaming.core.strategy.platform.SparkStreamingRuntime.processEvent(SparkStreamingRuntime.scala:122)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3$$anonfun$apply$1.apply(PlatformManager.scala:123)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3$$anonfun$apply$1.apply(PlatformManager.scala:122)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:122)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:116)
        at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
        at streaming.core.StreamingApp.main(StreamingApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/05/14 09:57:58 INFO spark.SparkContext: Invoking stop() from shutdown hook

**Comment by RebieKong** [comment]
启动命令里面的platform是不是选错了

**Comment by robin-su** [comment]
多谢，问题解决
