### ISSUE TITLE
执行测试用例失败

### ISSUE THREAD

**Issue by csxuyang** [byzer-org/byzer-lang#28]
我按照http://www.jianshu.com/p/d10edd6c7cf9进行执行测试
执行命令：
spark-submit   --class streaming.core.StreamingApp --master local --name test streamingpro-spark-0.4.14-SNAPSHOT-jar-with-dependencies.jar    -streaming.name test    -streaming.platform spark -streaming.job.file.path hdfs://XXXX:8020/streaming/test.json
但是执行报错
17/06/28 09:16:35 INFO Executor: Adding file:/tmp/spark-72838dd1-4362-453b-b6ac-86e8c888cca8/userFiles-7572807c-6955-4884-8cbf-af1af3cde129/streamingpro-spark-0.4.14-SNAPSHOT-jar-with-dependencies.jar to class loader
17/06/28 09:16:35 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1636 bytes result sent to driver
17/06/28 09:16:35 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 353 ms on localhost (1/1)
17/06/28 09:16:35 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
17/06/28 09:16:35 INFO DAGScheduler: ResultStage 0 (json at MockJsonCompositor.scala:31) finished in 0.369 s
17/06/28 09:16:35 INFO DAGScheduler: Job 0 finished: json at MockJsonCompositor.scala:31, took 0.588449 s
17/06/28 09:16:35 ERROR StrategyDispatcher: 调用链路异常
java.lang.ClassCastException: streaming.core.strategy.platform.SparkRuntime cannot be cast to streaming.core.strategy.platform.SparkStreamingRuntime
	at streaming.core.compositor.spark.streaming.source.MockInputStreamCompositor.result(MockInputStreamCompositor.scala:32)
	at streaming.core.strategy.SparkStreamingStrategy.result(SparkStreamingStrategy.scala:52)
	at serviceframework.dispatcher.StrategyDispatcher$$anonfun$dispatch$2.apply(StrategyDispatcher.scala:65)
	at serviceframework.dispatcher.StrategyDispatcher$$anonfun$dispatch$2.apply(StrategyDispatcher.scala:63)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at serviceframework.dispatcher.StrategyDispatcher.dispatch(StrategyDispatcher.scala:62)
	at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:120)
	at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:118)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:117)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/06/28 09:16:35 INFO SparkContext: Invoking stop() from shutdown hook

请问是哪里有问题呢

**Comment by csxuyang** [comment]
终于找到问题了，是我执行的时候应该选择spark_streaming，而不是spark，请关闭吧
