### ISSUE TITLE
提交应用报错

### ISSUE THREAD

**Issue by wtx626** [byzer-org/byzer-lang#30]
提交的命令为`./bin/spark-submit --master local[2] --class streaming.core.StreamingApp --name test ../spark-2.1.0/streamingpro-spark-2.0-0.4.15-SNAPSHOT.jar -streaming.name test -streaming.platform spark -streaming.job.file.path file:///./test.json`

出错的信息为
`Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at streaming.core.strategy.platform.PlatformManager$.platformNameMapping(PlatformManager.scala:212)
	at streaming.core.strategy.platform.PlatformManager$.getRuntime(PlatformManager.scala:194)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:82)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

**Comment by allwefantasy** [comment]
scala的版本问题。 能确保 ./bin/spark-submit的版本是2.1.0/1么？ 另外有没有可能环境变量导致识别到了错误的spark 版本。

**Comment by zhangxiaoqiong** [comment]
在SPARK_HOME目录下提交：./bin/spark-submit   --class streaming.core.StreamingApp --master yarn-cluster --name sql-interactive streamingpro-mlsql-1.1.3.jar    -streaming.name sql-interactive    -streaming.job.file.path file:///tmp/query.json -streaming.platform spark   -streaming.rest true   -streaming.driver.port 9003   -streaming.spark.service true -streaming.thrift false -streaming.enableHiveSupport true
报：
18/11/14 09:59:20 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at streaming.core.strategy.platform.PlatformManager$.platformNameMapping(PlatformManager.scala:213)
	at streaming.core.strategy.platform.PlatformManager$.getRuntime(PlatformManager.scala:193)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:81)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
18/11/14 09:59:20 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;)
18/11/14 09:59:30 ERROR yarn.ApplicationMaster: SparkContext did not initialize after waiting for 100000 ms. Please check earlier log output for errors. Failing the application.
18/11/14 09:59:30 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;)
18/11/14 09:59:30 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1541142863920_0021
18/11/14 09:59:30 INFO util.ShutdownHookManager: Shutdown hook called
