### ISSUE TITLE
测试流式计算示例代码错误

### ISSUE THREAD

**Issue by aaronsuscb** [byzer-org/byzer-lang#373]
1、kafka 0.11
2、向kafka发送测试数据
kafka-producer-perf-test.sh --num-records 1000000 --topic test-ref-1 --record-size 200 --throughput 100000 --producer-props bootstrap.servers=localhost:9092
3、运行流式测试案例
-- 设置该流式任务的名字。这个名字需要保持全局唯一。
set streamName="streamExample"

-- 加载kafka数据， 如果是0.8,0.9 那么分别使用kafka8 kafka9。如果是1.0 则
-- 直接使用kafka即可。指的注意是参数遵循原有spark规范，比如1.0参数你需要查看spark
-- 相关文档

load kafka.`` options `kafka.bootstrap.servers`="192.168.174.106:9092"
and `topics`="test-ref-1"
-- watermark的设置
-- and eventTimeCol="" and delayThreshold=""
as newkafkatable1;

-- 简单获得该周期的所有卡夫卡数据，不做任何处理。
select * from newkafkatable1
as table21;

-- 把数据增量保存到hdfs上，并且设置为json格式。 运行周期是10s,ck目录是 /tmp/cpl2
save append table21  
as json.`/tmp/abc2` 
options mode="Append"
and duration="10"
and checkpointLocation="/tmp/cpl2";
4、前端页面报如下错误
 Table or view not found: newkafkatable1; line 1 pos 14
5、后台报错如下
net.csdn.common.exception.RecordNotFoundException: 浣犺姹傜殑URL鍦板潃[/snippets/sql.js]涓嶅瓨鍦
      at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:90)
        at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
[2018-07-20 09:19:10,728][INFO ][modules.http.processor.impl] Completed 404 in 8ms      GET /snippets/sql.js

**Comment by allwefantasy** [comment]
This will not cause any problem.
We will close this issue. You can reopen it or create a new one if you have any other questions.
