### ISSUE TITLE
compiler erroe

### ISSUE THREAD

**Issue by ww102111** [byzer-org/byzer-lang#4]
在windows中git clone https://github.com/allwefantasy/csdn_common.git
编译第一个的时候
[ERROR] if (keys.length > 2) throw new ArgumentErrorException("不支持超过三级层次的参数传▒??");
[ERROR] ^
[ERROR]
[ERROR] Command line was: "C:\Program Files\Java\jdk1.8.0_60\jre..\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'D:\code\spark_test\csdn_common\target\apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by ww102111** [comment]
还有，
cher.scala:24
16/08/28 01:25:53 INFO FileInputFormat: Total input paths to process : 23
Exception in thread "main" java.io.IOException: Not a file: file:/run
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.ja                                                                             va:320)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.                                                                             scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:927)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.s                                                                             cala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.s                                                                             cala:111)

**Comment by allwefantasy** [comment]
感觉是windows 下的编码问题。

**Comment by ww102111** [comment]
我想请教下，这里面没看见怎么说mysql，都没有连接吗，还是用的自带的默认的

**Comment by allwefantasy** [comment]
系统并没有使用到任何存储。如果需要从MySQL 读取数据，参考： https://github.com/allwefantasy/streamingpro/blob/master/doc/components.md#jdbc-compositorsource-compositor  你可以可以使用标准的SQLSourceCompositor。不过目前MySQL数据源只能作为Join 数据，不能作为流式计算里的主数据源。批处理没问题。

**Comment by ww102111** [comment]
哦哦，那我还想写入到数据库，就像您以前简书写到的搭建一个工作流调度

**Comment by allwefantasy** [comment]
写入也可以。不过jdbc的写入没有完全遵循统一的标准。 晚点我几个JDBCOutputCompositor  即可。不过这个只能append/override 局限比较大。建议自己实现写入的规则。

**Comment by ww102111** [comment]
写入和修改，主要是想做实现您说的实现工作流调度器。生成工作流， 您上面的就可以了，然后如何真正的和mysql连接，这个得在streamingpro修改了吧

**Comment by allwefantasy** [comment]
不用  你在自己的项目里参考streaming.core.compositor.spark.streaming.output.SQLESOutputCompositor 自己实现一个，然后提交的时候带上自己的包就行。 并需要修改streamingpro

**Comment by ww102111** [comment]
那我先编译streamingpro，看看自己修改的效果

**Comment by ww102111** [comment]
执行build第二步：
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ServiceFramework: Could not resolve dependencies for project net.csdn:ServiceFramework:jar:1.3.2-SNAPSHOT-9.2.16: Could not find artifact net.csdn:ActiveORM:jar:1.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
我的git仓库里面明明是有的，呜呜

**Comment by mvasr7** [comment]
第一个问题是怎么解决的啊，我也遇到这个问题了。。。
