### ISSUE TITLE
streaming 任务读取kafka的topic有缓存吗？

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#575]
set streamName="streamExample";

load kafka9.`-` options `kafka.bootstrap.servers`="cdh150:9092"
and `topics`="test"
as newkafkatable1;

select "abc" as col1,decodeKafka(value) as col2 from newkafkatable1
as table21;

 -- output the the result to console.
save append table21  
as console.`` 
options mode="Append"
and duration="10"
and checkpointLocation="/tmp/cpl3";

我读取的是test的topic，怎么老是取之前运行的任务配置的testM呢？这个该怎么解决

java.util.NoSuchElementException: key not found: [testM,0]
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.hortonworks.spark.sql.kafka08.KafkaSource$$anonfun$3.apply(KafkaSource.scala:104)
	at com.hortonworks.spark.sql.kafka08.KafkaSource$$anonfun$3.apply(KafkaSource.scala:103)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.hortonworks.spark.sql.kafka08.KafkaSource.getBatch(KafkaSource.scala:103)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2$$anonfun$apply$7.apply(StreamExecution.scala:614)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2$$anonfun$apply$7.apply(StreamExecution.scala:610)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2.apply(StreamExecution.scala:610)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2.apply(StreamExecut

**Comment by allwefantasy** [comment]
你更换下 `checkpointLocation `试试。

**Comment by foreverjay** [comment]
> 你更换下 `checkpointLocation`试试。

可以了，多谢！

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other quetion.
