### ISSUE TITLE
pythonAlg例子 scala调用不成功

### ISSUE THREAD

**Issue by CoderOverflow** [byzer-org/byzer-lang#577]
[pythonAlg例子](https://www.jianshu.com/p/eeb2f1024819)

用最新的代码编译后

启动服务

```shell
./bin/spark-submit --class streaming.core.StreamingApp --master local[*] --name sql-interactive --jars ansj_seg-5.1.6.jar,nlp-lang-1.7.8.jar streamingpro-mlsql-1.1.3.jar -streaming.name sql-interactive -streaming.job.file.path file:///tmp/query.json -streaming.platform spark -streaming.rest true -streaming.driver.port 9003 -streaming.spark.service true -streaming.thrift false -streaming.deploy.rest.api true
```

webUI里面 输入命令 执行

```sql
load csv.`/opt/spark-2.2.0-bin-hadoop2.7/streamingpro/examples/sklearn_elasticnet_wine/wine-quality.csv` where header="true" and inferSchema="true" as data;

train data as PythonAlg.`/tmp/abcd` where pythonScriptPath="/opt/spark-2.2.0-bin-hadoop2.7/streamingpro/examples/sklearn_elasticnet_wine"
and keepVersion="true"
and enableDataLocal="true"
and dataLocalFormat="csv"
and fitParam.0.a="abcd"
as trainResult;

predict data as PythonAlg.`/tmp/abcd`;

register PythonAlg.`/tmp/abcd` as pj;
```

如果去除掉“register PythonAlg.`/tmp/abcd` as pj;” ，webUI可以见到返回结果，加上后webUI输出为空
运行后 执行 scala代码远程调用模型

执行 scala代码

```scala
import org.apache.http.client.fluent.{Form, Request}
object Test{
  def main(arg:Array[String]): Unit={
    val sql = "select pj(vec_dense(features)) as p1 "
    val res= Request.Post("http://192.168.123.71:9003/model/predict").bodyForm(Form.form().add("sql",sql)
      .add("data", s"""[{"features":[0.045,8.8,1.001,45.0,7.0,170.0,0.27,0.45,0.36,3.0,20.7]}]""")
      .add("dataType", "row")
      .build()).execute().returnContent().asString()
    println(res)
  }
}
```

后台返回错误

```
[2018-10-11 16:52:45,640][INFO ][org.apache.spark.sql.execution.SparkSqlParser] Parsing command:  pj(vec_dense(features)) as p1 
[2018-10-11 16:52:46,854][ERROR][modules.http             ] System processing error
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$5: (vector) => vector)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1075)
	at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:144)
	at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:48)
	at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:30)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$22.applyOrElse(Optimizer.scala:1147)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$22.applyOrElse(Optimizer.scala:1142)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:266)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:256)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$.apply(Optimizer.scala:1142)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$.apply(Optimizer.scala:1141)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2832)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2390)
	at org.apache.spark.sql.execution.datasources.json.WowJsonInferSchema$.toJson(WowJsonInferSchema.scala:76)
	at streaming.rest.RestPredictController.row2vecPredict(RestPredictController.scala:81)
	at streaming.rest.RestPredictController.modelPredict(RestPredictController.scala:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.modules.http.RestController.filter(RestController.java:139)
	at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:99)
	at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: unknown reason
	at org.apache.spark.api.python.WowBasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(WowPythonRunner.scala:311)
	at org.apache.spark.api.python.WowBasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(WowPythonRunner.scala:302)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.api.python.WowPythonRunner$$anon$1.read(WowPythonRunner.scala:385)
	at org.apache.spark.api.python.WowPythonRunner$$anon$1.read(WowPythonRunner.scala:363)
	at org.apache.spark.api.python.WowBasePythonRunner$ReaderIterator.hasNext(WowPythonRunner.scala:235)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at streaming.dsl.mmlib.algs.python.APIPredict$$anonfun$3.apply(APIPredict.scala:140)
	at streaming.dsl.mmlib.algs.python.APIPredict$$anonfun$3.apply(APIPredict.scala:114)
	at streaming.dsl.mmlib.algs.python.APIPredict$$anonfun$5$$anonfun$apply$3.apply(APIPredict.scala:150)
	at streaming.dsl.mmlib.algs.python.APIPredict$$anonfun$5$$anonfun$apply$3.apply(APIPredict.scala:149)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at streaming.dsl.mmlib.algs.python.APIPredict$$anonfun$5.apply(APIPredict.scala:149)
	at streaming.dsl.mmlib.algs.python.APIPredict$$anonfun$5.apply(APIPredict.scala:148)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:92)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:91)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1072)
	... 54 more
Caused by: org.apache.spark.api.python.WowBasePythonRunner$PythonException: Traceback (most recent call last):
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 166, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 55, in read_command
    command = serializer._read_with_length(file)
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 451, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 784, in _make_skel_func
    closure = _reconstruct_closure(closures) if closures else None
  File "/opt/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 776, in _reconstruct_closure
    return tuple([_make_cell(v) for v in values])
TypeError: 'int' object is not iterable

	at org.apache.spark.api.python.WowBasePythonRunner$ReaderIterator.handlePythonException(WowPythonRunner.scala:281)
	at org.apache.spark.api.python.WowPythonRunner$$anon$1.read(WowPythonRunner.scala:380)
	... 72 more
[2018-10-11 16:52:46,863][INFO ][modules.http.processor.impl] Completed 500 in 1334ms 	POST /model/predict
```

**Comment by CoderOverflow** [comment]
#642
