### ISSUE TITLE
Call python udf filed due to PyString

### ISSUE THREAD

**Issue by lordchao** [byzer-org/byzer-lang#603]
python udf:
```
set py_func = '''
def apply(self, s):
    from collections import Counter
    print(dict(Counter(s)))
    return dict(Counter(s))
''';

load script.`py_func` as py_script;

register ScriptUDF.`py_script` as count_board
options lang="python"
    and methodName="apply"
    and dataType="map(string,integer)"
;
```
where *s* is a python list and string inside.
Error message:
```
 java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
at org.python.modules.zipimport.zipimporter.readZipFile(zipimporter.java:404)
at org.python.modules.zipimport.zipimporter.readDirectory(zipimporter.java:366)
at org.python.modules.zipimport.zipimporter.zipimporter___init__(zipimporter.java:118)
at org.python.modules.zipimport.zipimporter.zipimporter___init__(zipimporter.java:84)
at org.python.modules.zipimport.zipimporter$exposed___new__.createOfType(Unknown Source)
at org.python.core.PyOverridableNew.new_impl(PyOverridableNew.java:12)
at org.python.core.PyType.invokeNew(PyType.java:494)
at org.python.core.PyType.type___call__(PyType.java:1706)
at org.python.core.PyType.__call__(PyType.java:1696)
at org.python.core.PyObject.__call__(PyObject.java:461)
at org.python.core.imp.getPathImporter(imp.java:480)
at org.python.core.imp.find_module(imp.java:530)
at org.python.core.imp.import_next(imp.java:840)
at org.python.core.imp.import_module_level(imp.java:959)
at org.python.core.imp.importName(imp.java:1062)
at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
at org.python.core.PyObject.__call__(PyObject.java:431)
at org.python.core.__builtin__.__import__(__builtin__.java:1232)
at org.python.core.imp.importFromAs(imp.java:1156)
at org.python.core.imp.importFrom(imp.java:1132)
at org.python.pycode._pyx14.extract_name$2(<string>:6)
at org.python.pycode._pyx14.call_function(<string>)
at org.python.core.PyTableCode.call(PyTableCode.java:167)
at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
at org.python.core.PyFunction.__call__(PyFunction.java:423)
at org.python.core.PyMethod.__call__(PyMethod.java:141)
at org.python.core.PyMethod.__call__(PyMethod.java:132)
at streaming.udf.PythonSourceUDF$$anon$2$$anonfun$apply$4.apply(PythonSourceUDF.scala:96)
```

**Comment by allwefantasy** [comment]
I use following code to test :

```sql
set py_func = '''
def apply(self, s):
    from collections import Counter
    print(dict(Counter(s)))
    return dict(Counter(s))
''';

load script.`py_func` as py_script;

register ScriptUDF.`py_script` as count_board
options lang="python"
    and methodName="apply"
    and dataType="map(string,integer)"
;

select count_board(array("你好","我好","大家好","你好")) as c as output;
```

The output seems ok:

```json
{ "我好": 1, "你好": 2, "大家好": 1 }
```

**Comment by allwefantasy** [comment]
update JPython version resolve this .
