### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tiger0526** [byzer-org/byzer-lang#634]
[2018-11-07 16:24:42,573][WARN ][org.eclipse.jetty.server.HttpChannel] /run/script
java.lang.NullPointerException
	at java.io.PrintWriter.write(PrintWriter.java:473)
	at net.csdn.modules.http.DefaultResponse.output(DefaultResponse.java:196)
	at net.csdn.modules.http.DefaultResponse.error(DefaultResponse.java:190)
	at net.csdn.modules.http.HttpServer$DefaultHandler.defaultErrorAction(HttpServer.java:159)
	at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:196)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
执行读取kafka流的时候点击运行就报错！大佬，这是为什么啊

**Comment by allwefantasy** [comment]
Can you paste your mlsql snippet?

**Comment by tiger0526** [comment]
谢谢老大，这个问题解决了

**Comment by allwefantasy** [comment]
Ok i will close this issue.
