### ISSUE TITLE
StreamingPro是否支持HDFS HA的方式

### ISSUE THREAD

**Issue by SeanZou** [byzer-org/byzer-lang#65]
./bin/spark-submit   --class streaming.core.StreamingApp \
--master local[2] \
--name sql-interactive \
/streamingpro/streamingpro-spark-2.0-1.0.0.jar   \
-streaming.name sql-interactive    \
-streaming.job.file.path file:///streamingpro/test.json \
-streaming.platform spark   \
-streaming.rest true   \
-streaming.driver.port 9004   \
-streaming.spark.service true
问题描述：
启动sqlserver方式如上，基于Scala 2.11 和spark 2.2.0 编译ServiceFramework和StreamingPro，按照README文档进行启动，报错如下：
Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: file:/streamingpro/query.json, expected: hdfs://haclusterdev
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:645)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:193)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:105)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:302)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:298)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:298)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:766)
	at streaming.common.HDFSOperator$.readFile(HDFSOperator.scala:21)
	at streaming.core.Dispatcher$.dispatcher(Dispatcher.scala:32)
	at streaming.core.strategy.platform.PlatformManager.findDispatcher(PlatformManager.scala:34)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:85)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
本人hdfs是采用HA的方式进行配置，看这个报错，是不是StreamingPro不支持HDFS HA的方式？

**Comment by allwefantasy** [comment]
如果是基于集群模式跑的，配置文件需要放到hdfs上哦。
