### ISSUE TITLE
MLSQL 1.1.3  runs on CDH  throws exception

### ISSUE THREAD

**Issue by wanghangyu817** [byzer-org/byzer-lang#670]

**Comment by wanghangyu817** [comment]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at streaming.core.strategy.platform.PlatformManager$.createRuntimeByPlatform(PlatformManager.scala:179)
	at streaming.core.strategy.platform.PlatformManager$.getRuntime(PlatformManager.scala:193)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:81)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)
Caused by: java.lang.AbstractMethodError
	at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
	at org.apache.spark.ps.cluster.PSDriverBackend.initializeLogIfNecessary(PSDriverBackend.scala:15)
	at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
	at org.apache.spark.ps.cluster.PSDriverBackend.log(PSDriverBackend.scala:15)
	at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
	at org.apache.spark.ps.cluster.PSDriverBackend.logInfo(PSDriverBackend.scala:15)
	at org.apache.spark.ps.cluster.PSDriverBackend.createRpcEnv(PSDriverBackend.scala:30)
	at org.apache.spark.ps.cluster.PSDriverBackend.start(PSDriverBackend.scala:53)
	at streaming.core.strategy.platform.SparkRuntime.createRuntime(SparkRuntime.scala:115)
	at streaming.core.strategy.platform.SparkRuntime.<init>(SparkRuntime.scala:32)
	at streaming.core.strategy.platform.SparkRuntime$.getOrCreate(SparkRuntime.scala:207)
	at streaming.core.strategy.platform.SparkRuntime.getOrCreate(SparkRuntime.scala)
	... 14 more

**Comment by allwefantasy** [comment]
The default MLSQL version compiled is spark 2.3.2. Do you run on spark 2.2? If so, please recompile MLSQL or upgrade your spark version to 2.3.2.

**Comment by wanghangyu817** [comment]
我在cdh5.15上，安装spark版本为2.3.0，运行时报错，有什么解决方案，或者有没有讨论组或者微信群

**Comment by allwefantasy** [comment]
You can download spark 2.3.2 form spark.apache.org manually and use the spark-submit in the new version to submit your MLSQL applictation.

**Comment by allwefantasy** [comment]
We will close this issue, if you have any questions please reopen it
