### ISSUE TITLE
Exception in thread "main" net.csdn.common.exception.FailedToResolveConfigException: Failed to resolve config path [strategy.v2.json]

### ISSUE THREAD

**Issue by ghost** [byzer-org/byzer-lang#8]
./bin/spark-submit   --class streaming.core.StreamingApp --master local[2] --name sql-interactive /data0/chaochao1/streamingpro-0.4.1-SNAPSHOT-online-2.0.0.jar  -streaming.name sql-interactive    -streaming.platform spark   -streaming.rest true   -streaming.driver.port 9004   -streaming.spark.service true

执行上面的命令，出现如下错误，是不是缺少，配置文件，参考哪里可以？
我参考下面的这个wiki
https://github.com/allwefantasy/streamingpro/wiki/%E5%88%A9%E7%94%A8StreamingPro%E5%AE%9E%E7%8E%B0SQL-%E4%BA%A4%E4%BA%92%E5%BC%8F%E6%9F%A5%E8%AF%A2

spark/spark-2.0.0-bin/config/strategy.v2.json], and classpath
    at net.csdn.common.env.Environment.resolveConfig(Environment.java:223)
    at net.csdn.common.env.Environment.resolveConfigAndLoadToString(Environment.java:186)
    at serviceframework.dispatcher.StrategyDispatcher.loadConfig(StrategyDispatcher.scala:115)
    at serviceframework.dispatcher.StrategyDispatcher$.getOrCreate(StrategyDispatcher.scala:218)
    at streaming.core.Dispatcher$.dispatcher(Dispatcher.scala:39)
    at streaming.core.strategy.platform.PlatformManager.findDispatcher(PlatformManager.scala:34)
    at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:87)
    at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
    at streaming.core.StreamingApp.main(StreamingApp.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by allwefantasy** [comment]
看这篇文章。 http://www.jianshu.com/p/ab2d34674ffb

里面加了一个细节点： 建立一个只有test.json,下里面的内容有：

```
{}
```

假设你放在/tmp目录下，然后启动即可：

```
cd  $SPARK_HOME

./bin/spark-submit   --class streaming.core.StreamingApp \
--master local[2] \
--name sql-interactive \
/tmp/streamingpro-0.4.1-SNAPSHOT-online-1.6.1.jar    \
-streaming.name sql-interactive    \
-streaming.job.file.path file:///tmp/test.json \
-streaming.platform spark   \
-streaming.rest true   \
-streaming.driver.port 9004   \
-streaming.spark.service true
```
