### ISSUE TITLE
[BUG] 1.1.6 Python udf fail when import datetime

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#809]
register ScriptUDF.`scriptTable` as dateRange options
and lang="python"
and dataType="array(string)"
and code='''
def apply(self, begin_time, end_time):
    import datetime
    range_list = ['a', 'b']
    return range_list
''';

select dateRange(1544715389, 1544715390) as a as outer;

error log 
`[2018-12-19 16:36:15,903][WARN ][org.apache.spark.scheduler.TaskSetManager] Lost task 0.0 in stage 0.0 (TID 0, zed-1.bigdata.com, executor 1): org.apache.spark.SparkException: Failed to execute user defined function($anon$3: (int, int) => array<string>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Traceback (most recent call last):
  File "<string>", line 6, in apply
  File "/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py", line 128, in <module>
  File "/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py", line 105, in _days_before_year
java.lang.NullPointerException
	at org.python.core.PyObject._add(PyObject.java:2136)
	at datetime$py._days_before_year$7(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py:105)
	at datetime$py.call_function(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at datetime$py.f$0(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py:2245)
	at datetime$py.call_function(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.util.importer.importer_load_module(importer.java:116)
	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:170)
	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
	at org.python.core.imp.loadFromLoader(imp.java:593)
	at org.python.core.imp.find_module(imp.java:547)
	at org.python.core.imp.import_next(imp.java:838)
	at org.python.core.imp.import_module_level(imp.java:957)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1076)
	at org.python.pycode._pyx0.apply$2(<string>:8)
	at org.python.pycode._pyx0.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at streaming.udf.PythonRuntimeCompileUDF$$anonfun$2.apply(PythonRuntimeCompileUDF.scala:84)
	at streaming.udf.PythonRuntimeCompileUDF$$anonfun$2.apply(PythonRuntimeCompileUDF.scala:82)
	at streaming.udf.RuntimeCompileUDF$$anon$3$$anonfun$apply$3.apply(RuntimeCompileUDF.scala:75)
	at streaming.udf.RuntimeCompileUDF$$anonfun$1.apply(RuntimeCompileUDF.scala:49)
	at streaming.udf.RuntimeCompileUDF$$anonfun$1.apply(RuntimeCompileUDF.scala:46)
	at streaming.udf.RuntimeCompileUDF$$anon$3.apply(RuntimeCompileUDF.scala:74)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException: java.lang.NullPointerException

	at org.python.core.Py.JavaError(Py.java:552)
	at org.python.core.PyTableCode.call(PyTableCode.java:180)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at datetime$py.f$0(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py:2245)
	at datetime$py.call_function(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.util.importer.importer_load_module(importer.java:116)
	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:170)
	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
	at org.python.core.imp.loadFromLoader(imp.java:593)
	at org.python.core.imp.find_module(imp.java:547)
	at org.python.core.imp.import_next(imp.java:838)
	at org.python.core.imp.import_module_level(imp.java:957)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1076)
	at org.python.pycode._pyx0.apply$2(<string>:8)
	at org.python.pycode._pyx0.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at streaming.udf.PythonRuntimeCompileUDF$$anonfun$2.apply(PythonRuntimeCompileUDF.scala:84)
	at streaming.udf.PythonRuntimeCompileUDF$$anonfun$2.apply(PythonRuntimeCompileUDF.scala:82)
	at streaming.udf.RuntimeCompileUDF$$anon$3$$anonfun$apply$3.apply(RuntimeCompileUDF.scala:75)
	at streaming.udf.RuntimeCompileUDF$$anonfun$1.apply(RuntimeCompileUDF.scala:49)
	at streaming.udf.RuntimeCompileUDF$$anonfun$1.apply(RuntimeCompileUDF.scala:46)
	at streaming.udf.RuntimeCompileUDF$$anon$3.apply(RuntimeCompileUDF.scala:74)
	... 13 more
Caused by: java.lang.NullPointerException
	at org.python.core.PyObject._add(PyObject.java:2136)
	at datetime$py._days_before_year$7(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py:105)
	at datetime$py.call_function(/yarn/nm/usercache/hdfs/appcache/application_1545028493322_1123/container_1545028493322_1123_01_000002/streamingpro.jar/Lib/datetime.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	... 49 more

[2018-12-19 16:36:15,912][INFO ][org.apache.spark.scheduler.cluster.YarnScheduler] Removed TaskSet 0.0, whose tasks have all completed, from pool default
[2018-12-19 16:36:15,917][INFO ][org.apache.spark.scheduler.cluster.YarnScheduler] Cancelling stage 0
[2018-12-19 16:36:15,919][INFO ][org.apache.spark.scheduler.DAGScheduler] ShuffleMapStage 0 (toJSON at RestController.scala:108) failed in 6.796 s due to Job aborted due to stage failure: Aborting TaskSet 0.0 because task 0 (partition 0) cannot run anywhere due to node and executor blacklist.  Blacklisting behavior can be configured via spark.blacklist.*.
[2018-12-19 16:36:15,925][INFO ][org.apache.spark.scheduler.DAGScheduler] Job 0 failed: collect at RestController.scala:108, took 7.160880 s
org.apache.spark.SparkException: Job aborted due to stage failure: Aborting TaskSet 0.0 because task 0 (partition 0) cannot run anywhere due to node and executor blacklist.  Blacklisting behavior can be configured via spark.blacklist.*.
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1524)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1512)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1511)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1511)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1739)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1694)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1683)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2031)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2052)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2071)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2096)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:278)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:2860)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2386)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2386)
	at org.apache.spark.sql.Dataset$$anonfun$54.apply(Dataset.scala:2841)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2840)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2386)
	at streaming.rest.RestController$$anonfun$script$2.apply$mcV$sp(RestController.scala:108)
	at streaming.core.StreamingproJobManager$.run(StreamingproJobManager.scala:43)
	at streaming.rest.RestController.script(RestController.scala:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.modules.http.RestController.filter(RestController.java:139)
	at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:99)
	at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by allwefantasy** [comment]
I try code like this, it works.
```scala
ScriptSQLExec.parse(
        """
          |register ScriptUDF.scriptTable as dateRange options
          |and lang="python"
          |and dataType="array(string)"
          |and code='''
          |def apply(self, begin_time, end_time):
          |    import datetime
          |    range_list = ['a', 'b']
          |    return range_list
          |''';
          |
          |select dateRange(1544715389, 1544715390) as a as outer;
        """.stripMargin, sq)
      spark.sql("select * from outer").show()

the result is :
+------+
|     a|
+------+
|[a, b]|
+------+
```
