### ISSUE TITLE
Is streaming2.3 available for spark2.3.0?

### ISSUE THREAD

**Issue by Eric-L90** [byzer-org/byzer-lang#847]
Env: 
```
streamingpro-spark_2.3-1.1.6
spark_2.3.0
```
SQL:
```
`kafka.bootstrap.servers`="localhost:9092"
and `failOnDataLoss`="false"
and `startingOffsets`="latest"
and `subscribe`="test"
and valueFormat="json"
and valueSchema="st(field(dstIp,string),field(sourceIp,string))"
as kafka_post_json;
```
Q:
When i run streming2.3 on spark2.3.0,there will be an error:
```
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SQLConf$.FROM_JSON_FORCE_NULLABLE_SCHEMA()Lorg/apache/spark/internal/config/ConfigEntry;
	at org.apache.spark.sql.WowJsonToStructs.<init>(WowJsonToStructs.scala:18)
	at streaming.source.parser.impl.JsonSourceParser.parse(JsonSourceParser.scala:12)
```
.
And then i changed spark2.3.0 to spark2.3.2, streaming2.3 worked well.
So does the streming2.3.2 only for the  spark2.3.2?

**Comment by allwefantasy** [comment]
It seems there is  compatibility problem  with  2.3.0.  Yes, for now, only spark 2.2.0,2.3.2,2.4.0 are tested.

**Comment by Eric-L90** [comment]
Ok, thanks
