### ISSUE TITLE
1.1.6启动报错

### ISSUE THREAD

**Issue by tiger0526** [byzer-org/byzer-lang#874]
请问使用这个streamingpro-mlsql-spark_2.3-1.1.6.jar启动的时候报错

Caused by: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.toSet()Lcom/google/common/collect/ImmutableSet;

老大这个是什么原因啊

**Comment by allwefantasy** [comment]
1. Can you paste the content of startup script?
2. What's the version of spark you runs?

**Comment by tiger0526** [comment]
CDH5.14,spark2.3的版本 
mlsql是streamingpro-mlsql-spark_2.3-1.1.6
刚看报错
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.bootstrap.Application.main(Application.java:18)
	at streaming.core.strategy.platform.PlatformManager.startRestServer(PlatformManager.scala:50)
	at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:100)
	at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
	at streaming.core.StreamingApp.main(StreamingApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoClassDefFoundError: net/csdn/jpa/JPA$CSDNORMConfiguration
	at net.csdn.bootstrap.Bootstrap.configureSystem(Bootstrap.java:82)
	at net.csdn.bootstrap.Bootstrap.main(Bootstrap.java:41)
	... 19 more
Caused by: java.lang.ClassNotFoundException: net.csdn.jpa.JPA$CSDNORMConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

**Comment by tiger0526** [comment]
mlsql1.3的启动是没有问题的

**Comment by allwefantasy** [comment]
Can you try MLSQL v1.1.7.1 ?

**Comment by allwefantasy** [comment]
We have released [v1.1.7.1](https://www.jianshu.com/p/c0d3f99b1e82) to fix this issue. 
The doc is [here](http://docs.mlsql.tech/v1.1.7.1/zh)

We will close this issue. If you find any problem again ,please reopen it or create a new one .

**Comment by zhangsancode** [comment]
My spark version CDH spark 2.4, I update my spark version from 2.2 to 2.4 today. And I update mlsql from 2.2_1.1.6 to 2.4_1.1.7.1

I use MLSQL V1.1.7.1，when i use http request driver port it have the error: 


[2019-07-31 19:12:58,603][WARN ][org.eclipse.jetty.util.thread.QueuedThreadPool]
java.lang.NoSuchMethodError: org.eclipse.jetty.util.StringUtil.toInt(Ljava/lang/String;)I
	at org.eclipse.jetty.http.HttpParser.handleKnownHeaders(HttpParser.java:854)
	at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:968)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1257)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
[2019-07-31 19:12:58,604][WARN ][org.eclipse.jetty.util.thread.QueuedThreadPool] Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@36d912c7 in qtp256993264{STARTED,100<=100<=1000,i=91,q=0}
