### ISSUE TITLE
Sometimes resource file will fail to load  In ET PythonParallelExt 

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#908]
The error message is like this:

```
126 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 74.0 failed 1 times, most recent failure: Lost task 2.0 in stage 74.0 (TID 218, localhost, executor driver): java.io.IOException: Unable to delete directory /tmp/__mlsql__/resource/a0eca6b7874e7bf47dd8938d30c744ae/b.
127 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541)
128 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
129 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at streaming.common.HDFSOperator$.copyToLocalFile(HDFSOperator.scala:160)
130 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at streaming.dsl.mmlib.algs.python.ResourceManager$$anonfun$loadResourceInTrain$2.apply(ResourceManager.scala:36)
131 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at streaming.dsl.mmlib.algs.python.ResourceManager$$anonfun$loadResourceInTrain$2.apply(ResourceManager.scala:31)
132 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
133 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at streaming.dsl.mmlib.algs.python.ResourceManager.loadResourceInTrain(ResourceManager.scala:31)
134 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at streaming.dsl.mmlib.algs.python.PythonTrain$$anonfun$4.apply(PythonTrain.scala:136)
135 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at streaming.dsl.mmlib.algs.python.PythonTrain$$anonfun$4.apply(PythonTrain.scala:105)
136 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:853)
137 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:853)
138 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
139 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
140 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
141 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
142 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
143 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
144 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
145 - 2019-01-16T11:55:55.797Z -[mlsql-algo3]-[mlsql5]: at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
```
Sometimes org.apache.commons.io.FileUtils will fail even the file is deleted .

**Comment by allwefantasy** [comment]
We will use `deleteQuietly` instead of `forceDelete`
