### ISSUE TITLE
stream/jobs/running java.lang.NullPointerException

### ISSUE THREAD

**Issue by Eric-L90** [byzer-org/byzer-lang#912]
```
Env:
mlsql-spark_2.3-1.1.7
mlsql-api-console-1.0-SNAPSHOT.jar
```
提交task之后，点击任务列表报错:
```
[2019-01-16 19:10:50,294][WARN ][org.eclipse.jetty.server.HttpChannel] /stream/jobs/running
java.lang.NullPointerException
	at java.io.PrintWriter.write(PrintWriter.java:473)
	at net.csdn.modules.http.DefaultResponse.output(DefaultResponse.java:196)
	at net.csdn.modules.http.DefaultResponse.error(DefaultResponse.java:190)
	at net.csdn.modules.http.HttpServer$DefaultHandler.defaultErrorAction(HttpServer.java:159)
	at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:196)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```
另外，MLSQL Web Console 里面的Job按钮点不点的没反应。那个是不是还没有开发完毕？

**Comment by allwefantasy** [comment]
To check your running jobs by this [tutorial](http://docs.mlsql.tech/v1.1.7/zh/jobs/), but for now it only supports batch jobs.

Yes ,the button we will remove it later.
