### ISSUE TITLE
A logic error occurred and the state of yarn is still Successed

### ISSUE THREAD

**Issue by moranrr** [byzer-org/byzer-lang#954]
When I runs on the application mode，If sql has a logic error, the finalstates of yarn is still success。
I found that this issue has been fixed [https://github.com/allwefantasy/streamingpro/pull/696](#696 )。
So I rebuilt the ServiceFramework and mlsql, and i set  ``-streaming.mode.application.fails_all true``， but I still can't expect the result。
```
19/02/26 17:48:19 INFO SparkRuntime: mlsql server start with configuration!
19/02/26 17:48:19 INFO SparkRuntime: ------------------------------------------------------------------------------------------------
19/02/26 17:48:19 INFO SparkRuntime: |streaming.job.file.path             |hdfs://xxxx.json|
19/02/26 17:48:19 INFO SparkRuntime: |streaming.mode.application.fails_all|true                                                     |
19/02/26 17:48:19 INFO SparkRuntime: |streaming.carbondata.store          |hdfs://xxxx/CarbonStore                  |
19/02/26 17:48:19 INFO SparkRuntime: |streaming.enableHiveSupport         |true                                                     |
19/02/26 17:48:19 INFO SparkRuntime: |streaming.enableCarbonDataSupport   |true                                                     |
19/02/26 17:48:19 INFO SparkRuntime: |streaming.name                      |failtest                                                 |
19/02/26 17:48:19 INFO SparkRuntime: |streaming.platform                  |spark                                                    |
19/02/26 17:48:19 INFO SparkRuntime: ------------------------------------------------------------------------------------------------
19/02/26 17:48:19 INFO SparkSessionCacheManager: Scheduling SparkSession cache cleaning every 60 seconds
19/02/26 17:48:19 INFO SparkRuntime: register functions.....
19/02/26 17:48:19 INFO CarbonEnv: main Initializing CarbonEnv, store location: hdfs://xxx/CarbonStore
19/02/26 17:48:19 INFO CarbonMetaStoreFactory: main File based carbon metastore is enabled
19/02/26 17:48:19 INFO CarbonEnv: main Initialize CarbonEnv completed...
19/02/26 17:48:19 INFO CarbonSparkSqlParser: Parsing command: select 1 as a
19/02/26 17:48:20 INFO CarbonSparkSqlParser: Parsing command: command
19/02/26 17:48:20 INFO CarbonLateDecodeRule: main skip CarbonOptimizer
19/02/26 17:48:20 INFO CarbonLateDecodeRule: main Skip CarbonOptimizer
19/02/26 17:48:20 INFO Version: Elasticsearch Hadoop v6.2.4 [0dadc1ea14]
19/02/26 17:48:21 ERROR StrategyDispatcher: 调用链路异常
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3628)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1493)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:62)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation.<init>(JDBCRelation.scala:114)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:52)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:307)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
        at streaming.core.compositor.spark.source.MultiSQLSourceCompositor$$anonfun$result$1.apply(MultiSQLSourceCompositor.scala:65)
        at streaming.core.compositor.spark.source.MultiSQLSourceCompositor$$anonfun$result$1.apply(MultiSQLSourceCompositor.scala:46)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at streaming.core.compositor.spark.source.MultiSQLSourceCompositor.result(MultiSQLSourceCompositor.scala:46)
        at streaming.core.strategy.SparkStreamingStrategy.result(SparkStreamingStrategy.scala:70)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$dispatch$2.apply(StrategyDispatcher.scala:69)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$dispatch$2.apply(StrategyDispatcher.scala:67)
        at scala.collection.immutable.List.flatMap(List.scala:327)
        at serviceframework.dispatcher.StrategyDispatcher.dispatch(StrategyDispatcher.scala:66)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:147)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:141)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:140)
        at streaming.core.StreamingApp$.main(StreamingApp.scala:32)
        at streaming.core.StreamingApp.main(StreamingApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3628)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1493)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:62)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation.<init>(JDBCRelation.scala:114)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:52)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:307)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
        at streaming.core.compositor.spark.source.MultiSQLSourceCompositor$$anonfun$result$1.apply(MultiSQLSourceCompositor.scala:65)
        at streaming.core.compositor.spark.source.MultiSQLSourceCompositor$$anonfun$result$1.apply(MultiSQLSourceCompositor.scala:46)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at streaming.core.compositor.spark.source.MultiSQLSourceCompositor.result(MultiSQLSourceCompositor.scala:46)
        at streaming.core.strategy.SparkStreamingStrategy.result(SparkStreamingStrategy.scala:70)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$dispatch$2.apply(StrategyDispatcher.scala:69)
        at serviceframework.dispatcher.StrategyDispatcher$$anonfun$dispatch$2.apply(StrategyDispatcher.scala:67)
        at scala.collection.immutable.List.flatMap(List.scala:327)
        at serviceframework.dispatcher.StrategyDispatcher.dispatch(StrategyDispatcher.scala:66)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:147)
        at streaming.core.strategy.platform.PlatformManager$$anonfun$run$3.apply(PlatformManager.scala:141)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:140)
        at streaming.core.StreamingApp$.main(StreamingApp.scala:32)
        at streaming.core.StreamingApp.main(StreamingApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/02/26 17:48:21 INFO SparkContext: Invoking stop() from shutdown hook
19/02/26 17:48:21 INFO AbstractConnector: Stopped Spark@149b4d20{HTTP/1.1,[http/1.1]}{0.0.0.0:4041}
19/02/26 17:48:21 INFO SparkUI: Stopped Spark web UI at http://10.86.210.16:4041
19/02/26 17:48:21 INFO YarnClientSchedulerBackend: Interrupting monitor thread
19/02/26 17:48:21 INFO YarnClientSchedulerBackend: Shutting down all executors
19/02/26 17:48:21 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
19/02/26 17:48:21 INFO SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
19/02/26 17:48:21 INFO YarnClientSchedulerBackend: Stopped
19/02/26 17:48:21 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/02/26 17:48:21 INFO MemoryStore: MemoryStore cleared
19/02/26 17:48:21 INFO BlockManager: BlockManager stopped
19/02/26 17:48:21 INFO BlockManagerMaster: BlockManagerMaster stopped
19/02/26 17:48:21 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/02/26 17:48:21 INFO SparkContext: Successfully stopped SparkContext
19/02/26 17:48:21 INFO ShutdownHookManager: Shutdown hook called
19/02/26 17:48:21 INFO ShutdownHookManager: Deleting directory /tmp/spark-5820f249-03bb-46e1-a18e-a846381a1df7
```:

the yarn finalstatus is also SUCCESSED?

**Comment by allwefantasy** [comment]
Yes, for now, MLSQL just fails the application, but the status of yarn will still be `SUCCESSED`. Can you try to use service mode?

**Comment by allwefantasy** [comment]
And Serviceframework have been uploaded to maven central repository, and there is no need to build it manually.
